# Generated by Django 3.1.2 on 2020-11-06 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default=None, max_length=200)),
                ('asset_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('purchased_from', models.CharField(blank=True, max_length=200, null=True)),
                ('date_acquired', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['date_acquired'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['manufacturer_name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(max_length=200, null=True)),
                ('date_transferred', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.acquisition')),
                ('department_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.department')),
                ('location_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.location')),
            ],
            options={
                'ordering': ['date_transferred'],
            },
        ),
        migrations.AddField(
            model_name='acquisition',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.manufacturer'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='post_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
