# Generated by Django 3.1.2 on 2020-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
