# Generated by Django 3.1.2 on 2020-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20201110_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
