# Generated by Django 3.1.2 on 2020-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20201110_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
